name: CD

on:
  push:
    branches:
      - main
    paths:
      frontend/**
  workflow_dispatch:

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout

        uses: actions/checkout@v4

      - name: setup
        working-directory: frontend
        run: npm install

      - name: node test
        working-directory: frontend
        run: npm test

  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout

        uses: actions/checkout@v4

      - name: Build React app
        working-directory: frontend
        run: docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .
      - name: run
        working-directory: frontend
        run: docker run --name mp-frontend -p 3000:3000 -d mp-frontend

  ecr_login:
    name: ecr_login
    runs-on: ubuntu-latest
    steps:

      - name: checkout

        uses: actions/checkout@v4
     
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

     
      - name: login
        working-directory: frontend
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 153740163786.dkr.ecr.us-east-1.amazonaws.com

      - name: tagging
        working-directory: frontend
        run: docker tag mp-frontend:$latest 153740163786.dkr.ecr.us-east-1.amazonaws.com/coworking-checkin:$GIT_SHA

      - name: push
        working-directory: frontend
        run: docker push 153740163786.dkr.ecr.us-east-1.amazonaws.com/coworking-checkin:$GIT_SHA



  
     