name: Movie

on:
  pull_request:
    branches:
      - main
    paths:
      - frontend/**
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
    
      - name: setup nodejs
        working-directory: frontend
        run: npm install

      - name: setup
        working-directory: frontend
        run: npm ci


      - name: node lint
        working-directory: frontend
        run: npx eslint . --fix
        #run: npm run lint
        continue-on-error: false

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup nodejs
        working-directory: frontend
        run: npm install

      - name: test1
        working-directory: frontend
        run: npm test

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [lint, test]
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup nodejs
        working-directory: frontend
        run: npm ci


      - name: Build React app
        working-directory: frontend
        run: docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .
      - name: run
        working-directory: frontend
        run: docker run --name mp-frontend -p 3000:3000 -d mp-frontend

  ecr_login:
    name: ecr_login
    runs-on: ubuntu-latest
    steps:
      - name: login
        working-directory: frontend
        run: aws ecr get-login-password --region us-east-1 docker login --username AWS \
             | --password-stdin 153740163786.dkr.ecr.us-east-1.amazonaws.com/project

     
  


