name: Movie

on:
  pull_request:
    branches:
      - main
    paths:
      - frontend/**
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
    
      - name: setup nodejs
        working-directory: frontend
        run: npm install

      - name: setup
        working-directory: frontend
        run: npm ci

      - name: ftft
        working-directory: frontend
        run: npx prettier --write .


      - name: node lint
        working-directory: frontend
        run: npm run lint

  


